apiVersion: batch/v1
kind: Job
metadata:
  name: job-factorial
spec:
  completions: 5
  parallelism: 2
  template:
    spec:
      containers:
      - name: worker
        image: busybox
        command: ["sh", "-c", "Calculando el factorial de 5; sleep 3; echo '120'"]
      restartPolicy: OnFailure