apiVersion: apps/v1
kind: Deployment
metadata: {name: cpu-hog, namespace: dev}
spec:
  replicas: 2
  selector: {matchLabels: {app: cpu-hog}}
  template:
    metadata: {labels: {app: cpu-hog}}
    spec:
      containers:
      - name: stress
        image: vish/stress
        resources:
          requests:
            cpu: "0.5"
            memory: "100Mi"
          limits:
            memory: "200Mi"
            cpu: "1"
        args: ["-cpu", "1", "-timeout", "20s"]